
   <header>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container">

        <a class="navbar-brand" href="homeR.html"><img src="img/internet.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#textoNavbar" aria-controls="textoNavbar" 
        aria-expanded="false" aria-label="Alterna navegação">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="textoNavbar">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Frequência</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/frequenciaP?pesquisarPor=recuperar">Consultar</a> 
            </div>
          </li>

          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Conteúdo</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="conteudoR?pesquisarPor=recuperar">Consultar</a>
            </div>
          </li>

            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Atividade</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="consultar?acao=recuperar">Consultar</a>
            </div>
          </li>

        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Comunicar</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="comunicarR?pesquisarPor=inserir">Realizar</a>
            </div>
          </li>
        
         <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Comunicados</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="comunicadosR.html">Consultar</a>
            </div>
          </li>
          
          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Observações</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="observacaoConsultarR?pesquisarPor=recuperar">Consultar</a>
            </div>
          </li>
        </ul>



        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php print_r($this->view->nomePr['nome']) ?></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Responsável</a>
              <a class="dropdown-item" href="/">Sair</a> 
            </div>
          </li>
        </ul>

      </nav>
    </header>
    <div class="container ">

        <div class="col-sm-12">
          <div class="container">
            <div class="row">
              <div class="col">
                <h4>Página inicial</h4>
                <hr/><p>Olá, <?php print_r($this->view->nomePr['nome']) ?>.</p>
                   <p>Seja bem vindo(a), ao sistema de acompanhamento escolar.</p>
                  <p>Você pode, através dos menus de navegação acima, entrar nas páginas de conteúdos, atividades, frequência, comunicação, observações.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>