      <script>
     function editar() {
        alert("Tarefa inserida com sucesso!");
      }
    </script>
        <header>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container">
        
        <a class="navbar-brand" href="/homeP"><img src="img/internet.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#textoNavbar" aria-controls="textoNavbar" aria-expanded="false" aria-label="Alterna navegação">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="textoNavbar">
         <ul class="navbar-nav mr-auto">
          
           <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Diário</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/diario?pesquisarPor=recuperar">Realizar frequência</a>
            <a class="dropdown-item" href="/frequenciaP?pesquisarPor=recuperar">Consultar</a>
          </li>
          
          
          
         <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Conteúdo</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/conteudo?pesquisarPor=recuperar">Cadastrar conteúdo</a>
               <a class="dropdown-item" href="/visualizarConteudo?pesquisarPor=recuperar">Consultar</a>
          </li>

            <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Atividade</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="/novaAtividade">Cadastrar atividade</a>
                <a class="dropdown-item" href="/consultar?acao=recuperar">Consultar</a> 
              </div>
            </li>

         <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Observação</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/observacao?pesquisarPor=recuperar">Realizar observação</a>
            <a class="dropdown-item" href="/observacaoConsultarP?pesquisarPor=recuperar">Consultar</a>
          </li>

         <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Comunicar</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/comunicarP?pesquisarPor=recuperar">Realizar</a>
          </li>

        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Comunicados</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/comunicadosP?pesquisarPor=recuperar">Consultar</a>
          </li>
          
        </ul>
        
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php print_r($this->view->nomePr['nome']) ?></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Professor</a>
              <a class="dropdown-item" href="/">Sair</a> 
            </div>
          </li>
        </ul>        
      </div>
    </div>    
  </nav>
</header>


        <div class="col-md-12">
  <div class="container">
    <div class="row">
      <div class="col">
        <h4>Cadastrar Atividade</h4>
        <hr/>
        <form method="post" action="/novaAtividade?acao=inserir">

          <div class="form-group">

            <div class="row">

               <div class="col">

               <label class="labelM">Turma</label>

               <select class="form-control "id="turma" name="Turma_idTurma">
                <option value="" disabled selected>Selecione uma turma.</option>
                 <?php foreach ($this->view->turmas as $turma) { ?>
                  <option  value="<?php print_r ($turma['serie'])?>"><?php print_r($turma['serie'])?></option>
                   <?php }?>
              </select>
            </div>

              <div class="col">

            <label class="labelM" for="conteudo">Conteúdo</label> 
           
          <select class="form-control" id="conteudo" name="Conteudo_idConteudo"  >

              <option value="" disabled selected>Selecione um conteúdo.</option>

    
                        <?php foreach ($this->view->conteudos as $conteudo) {?>
            
                       
                        <option value="<?php print_r ($conteudo['idConteudo']) ?>"><?php print_r($conteudo['materia'])?> - <?php echo  mb_strimwidth($conteudo['descricao'],0 , 45, "...")?> </option>

      

                      <?php  }?>

                      
            </select>

            </div>

           
        </div>

         <div class="row">

           <div class="col">

            <label class="labelM">Atividade</label>

            <input type="text" class="form-control" name="nome" placeholder="Exemplo: Tabuada de 5">

          </div>

              <div class="col">

            <label class="labelM">Data final da atividade</label>
            <input class="form-control"  type="Date" name="dataFim">
          </div>
          </div>
          <input class="btn btn-primary" value="Cadastrar" name="salvar" type="submit" style="margin-top: 5px">
        </form>
        </div>
      </div>
    </div>
  </div>
</div>