
			<header id="cabecalho">
			<nav id="menu">
			
			</nav>
			</header>
			<div class="container">
    			<div class="row">
    				<div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    					<div class="card card-signin my-5">
       				    	<div class="card-body">
       				    		<div class="form-signin">
       				    			<div class="form-label-group">
                          <h5 class="card-title text-center"><img src="img/internet.png"> </h5>
       				    				<h5 class="card-title text-center">Sistema de acompanhamento escolar</h5>
       				    				<h5 class="card-title text-center">Bem-Vindo</h5>
       				    				<h5 class="card-title text-center">Selecione o perfil desejado</h5>
       				    				<a href="/loginP" class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" >Sou Professor</a>
               							<a href="/loginR" class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sou Responsável</a>
    					 			</div>
    					 		</div>
    						</div>
    					</div>
    				</div>
    			</div>
			</div>
